CREATE DATABASE prog9_db;

USE prog9_db;

CREATE TABLE grid_layouts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    layout_name VARCHAR(100) NOT NULL,
    configuration JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
